/*
 * Copyright (C) 2025 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generate_arm64_disassembler.py
 * from ARM64 ISA XML documentation
 */


#include "config.h"

#if ENABLE(ARM64_DISASSEMBLER)

#include "A64DOpcodeNew.h"
#include <stdio.h>

namespace JSC { namespace ARM64Disassembler {

A64DOpcodeNew::A64DOpcodeNew(uint32_t* startPC, uint32_t* endPC)
    : m_startPC(startPC)
    , m_endPC(endPC)
    , m_currentPC(nullptr)
    , m_opcode(0)
{
    m_formatBuffer[0] = '\0';
}

void A64DOpcodeNew::setPCAndOpcode(uint32_t* pc, uint32_t opcode)
{
    m_currentPC = pc;
    m_opcode = opcode;
    m_formatBuffer[0] = '\0';
}

const char* A64DOpcodeNew::disassemble(uint32_t* currentPC)
{
    setPCAndOpcode(currentPC, *currentPC);

    // Find matching instruction
    const InstructionTableEntry* entry = findInstruction(m_opcode);

    // Format instruction
    formatInstruction(entry, m_opcode, nullptr, m_formatBuffer, BufferSize);

    return m_formatBuffer;
}

}} // namespace JSC::ARM64Disassembler

#endif // ENABLE(ARM64_DISASSEMBLER)
