/*
 * Copyright (C) 2025 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generate_arm64_disassembler.py
 * from ARM64 ISA XML documentation
 */


#pragma once

#include <stdint.h>
#include <stddef.h>

namespace JSC { namespace ARM64Disassembler {

class A64DOpcode;

// Instruction encoding table entry
struct InstructionTableEntry {
    const char* name;
    const char* mnemonic;
    uint32_t mask;
    uint32_t pattern;
    uint16_t operandDataOffset;  // Offset into operand data table
    uint8_t operandCount;
};

// Operand descriptor
struct OperandDescriptor {
    uint8_t type;       // OperandType
    uint8_t format;     // Format variant
    uint8_t field1;     // Field index 1
    uint8_t field2;     // Field index 2
};

// Operand types
enum OperandType {
    OP_NONE = 0,
    OP_REGISTER_X,
    OP_REGISTER_W,
    OP_REGISTER_SP,
    OP_REGISTER_FP,
    OP_REGISTER_V,
    OP_REGISTER_Z,
    OP_REGISTER_P,
    OP_IMMEDIATE,
    OP_IMMEDIATE_HEX,
    OP_IMMEDIATE_SHIFTED,
    OP_LABEL,
    OP_CONDITION,
    OP_SHIFT_TYPE,
    OP_EXTEND_TYPE,
    OP_MEMORY_BASE,
    OP_MEMORY_BASE_OFFSET,
    OP_MEMORY_PRE_INDEX,
    OP_MEMORY_POST_INDEX,
};

// Instruction table
extern const InstructionTableEntry g_instructionTable[];
extern const size_t g_instructionTableSize;

// Operand descriptor table
extern const OperandDescriptor g_operandTable[];

// Find instruction encoding for opcode
const InstructionTableEntry* findInstruction(uint32_t opcode);

// Format instruction
void formatInstruction(const InstructionTableEntry* entry, uint32_t opcode,
                      A64DOpcode* context, char* buffer, size_t bufferSize);

}} // namespace JSC::ARM64Disassembler
