/*
 * Copyright (C) 2025 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generate_arm64_disassembler.py
 * Complete implementation with field metadata and all formatters
 */


#pragma once

#include <stdint.h>
#include <stddef.h>

namespace JSC::ARM64Disassembler {

enum class OperandType : uint8_t;

// Instruction entry
struct InstructionEntry {
    const char* mnemonic;
    uint32_t mask;
    uint32_t pattern;
    uint16_t operandOffset;
    uint8_t operandCount;
    uint8_t flags;
};

// Operand descriptor
struct OperandDesc {
    OperandType type;
    uint8_t subtype;
    uint8_t field1Start;
    uint8_t field1Width;
    uint8_t field2Start;
    uint8_t field2Width;
};

// Field metadata
struct FieldMeta {
    const char* name;
    uint8_t bitStart;
    uint8_t bitWidth;
};

// Tables
extern const InstructionEntry g_instructionTable[];
extern const size_t g_instructionTableSize;
extern const OperandDesc g_operandTable[];
extern const FieldMeta g_fieldMetadata[];
extern const size_t g_fieldMetadataSize;

// API
const InstructionEntry* findInstruction(uint32_t opcode);
void formatInstruction(const InstructionEntry* entry, uint32_t opcode, uint32_t* pc, uint32_t* startPC, uint32_t* endPC, char* buffer, size_t bufferSize);

} // namespace JSC::ARM64Disassembler
